import { basePreset } from "@9thround/config/eslint-preset";

export default [
  {
    // Autogenerated by Next.js on every dev/build run (see the file's own
    // "This file should not be edited" comment) — its triple-slash
    // references are Next's own convention, not something to fix here.
    ignores: ["**/dist/**", "**/.next/**", "**/.expo/**", "**/.turbo/**", "**/coverage/**", "**/next-env.d.ts"],
  },
  ...basePreset,
  {
    files: ["**/*.config.js", "**/*.config.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: { module: "writable", require: "readonly", process: "readonly", __dirname: "readonly" },
    },
  },
  {
    // Unanchored so this also reaches each workspace's own scripts/ dir
    // (e.g. apps/site/scripts/localize-next.mjs), not just a repo-root one.
    files: ["**/scripts/**/*.mjs"],
    languageOptions: {
      globals: { console: "readonly", process: "readonly" },
    },
    rules: {
      // A postinstall/build script reporting its own progress is exactly what console.log is for.
      "no-console": "off",
    },
  },
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        // typescript-eslint's Project Service auto-discovers the right
        // tsconfig.json per file across the monorepo's many packages —
        // required for type-aware rules like no-floating-promises.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
];
