/** User-facing wording for the database's RACE_* error codes (the raw server text is the fallback). */
const MESSAGES: Record<string, string> = {
  RACE_REGISTRATION_CLOSED: "Registration is not open for this event.",
  RACE_ALREADY_REGISTERED: "This athlete is already registered for the event.",
  RACE_WAIVER_REQUIRED: "The waiver must be accepted to register.",
  RACE_EMERGENCY_CONTACT_REQUIRED: "Enter an emergency contact name and phone number.",
  RACE_INVALID_NAME: "Enter the athlete's full name.",
  RACE_INVALID_PHONE: "Enter a valid phone number.",
  RACE_INVALID_EMAIL: "Enter a valid email address.",
  RACE_INVALID_DOB: "Check the date of birth.",
  RACE_INVALID_CATEGORY: "Choose a category.",
  RACE_CATEGORY_GENDER: "That category does not match the athlete's gender.",
  RACE_CATEGORY_AGE: "The athlete is too young for that category on the event date.",
  RACE_DOB_REQUIRED: "Date of birth is required for that category.",
  RACE_PUSHUP_STYLE_NOT_ALLOWED: "That push-up style is not available for this category.",
  RACE_PUSHUP_STYLE_LOCKED: "Push-up style can no longer be changed — Station 02 has started.",
  RACE_NOT_FOUND: "Not found.",
  RACE_FORBIDDEN: "Your account is not allowed to do that for this event.",
  RACE_HEATS_LOCKED: "Heats are locked. Use an authorized change with a reason.",
  RACE_REASON_REQUIRED: "A reason is required.",
  RACE_ALREADY_PAID: "This registration is already paid.",
  RACE_AMOUNT_MISMATCH: "A different amount needs a note explaining why.",
  RACE_REGISTRATION_CANCELLED: "This registration is cancelled.",
  RACE_REFUND_REQUIRED: "Refund the payment first.",
  RACE_ATHLETE_ALREADY_CHECKED_IN: "The athlete is already checked in — use the race-control withdrawal workflow.",
  RACE_INVALID_PAYMENT_METHOD: "Choose cash, InstaPay, Vodafone Cash, card POS or bank transfer.",
  RACE_INVALID_PAYMENT_TRANSITION: "That payment cannot be changed that way.",
  RACE_PAYMENT_REQUIRED: "The registration must be paid or waived first.",
  RACE_HEAT_FULL: "That heat is full (9 athletes).",
  RACE_NUMBERS_EXHAUSTED: "No race numbers left for this event.",
  RACE_CHECKIN_NOT_OPEN: "Check-in opens when heats are locked.",
  RACE_NO_HEAT: "This athlete has no heat yet — ask the Event Manager to assign one.",
  RACE_NOT_CONFIRMED: "Payment is not confirmed — send the athlete to the payment desk first.",
  RACE_CHECKIN_NOT_ELIGIBLE: "This athlete cannot be checked in (missed start, withdrawn or already racing).",
  RACE_NOT_STARTED: "The race has not started yet.",
  RACE_ALREADY_STARTED: "The race has already started — START EVENT can only be pressed once.",
  RACE_HEATS_NOT_LOCKED: "Lock the heats before starting the event.",
  RACE_NO_ATHLETES: "No heat has any athlete yet.",
  RACE_ALREADY_PAUSED: "The race is already paused.",
  RACE_NOT_PAUSED: "The race is not paused.",
  RACE_EVENT_FINISHED: "The race has finished.",
  RACE_EVENT_NOT_LIVE: "That can only be done while the race is live.",
  RACE_CONFIG_LOCKED: "Timing settings are frozen once heats are locked.",
  RACE_SLOT_NOT_ASSIGNED: "That slot has no athlete (already skipped, empty or not yet assigned).",
  RACE_SKIP_WINDOW_CLOSED: "Too late to skip — the athlete is past their Station 01 window.",
  RACE_NOT_RACING: "Only an athlete who is racing can be marked DNF.",
  RACE_PREVIOUS_HEAT_NOT_STARTED: "Start the previous heat first.",
  RACE_HEAT_ALREADY_STARTED: "That heat has already started.",
  RACE_HEAT_NOT_MANUAL: "That heat starts automatically — it does not need a manual start.",
  RACE_HEAT_NOT_CANCELLABLE: "That heat cannot be closed — it has already started or is finished.",
  RACE_HEAT_EMPTY: "That heat has no athletes.",
  RACE_CORRECTION_SAME_ATHLETE: "Choose a different athlete.",
  RACE_CORRECTION_DIFFERENT_HEAT: "Both athletes must be in the same heat.",
  RACE_CORRECTION_NOT_ELIGIBLE: "The corrected athlete must be confirmed and not already checked in.",
  RACE_NOT_CHECKED_IN: "That athlete is not checked in.",
  RACE_ATHLETE_ALREADY_STARTED: "That athlete has already started — use SKIP ATHLETE instead.",
  RACE_NOT_DNS: "Only a DNS athlete can be overridden.",
  RACE_NO_SLOT_AVAILABLE: "NO SLOT AVAILABLE — every free slot is needed by athletes already waiting. Nobody can be displaced.",
  RACE_ATHLETE_HAS_SLOT: "That athlete already holds a start slot and cannot be moved.",
  RACE_MOVE_NOT_LATER: "An athlete can only be moved to a LATER heat.",
  RACE_MOVE_NOT_ELIGIBLE: "That athlete cannot be moved (already racing or finished).",
  RACE_TIE_GROUP_CHANGED: "A tie group changed unexpectedly — tell the Event Manager.",
};

export function describeRaceError(code: string, serverMessage?: string): string {
  return MESSAGES[code] ?? serverMessage ?? "Something went wrong. Try again.";
}

/** Extracts `RACE_XXX` from a Postgres exception message ("RACE_XXX: detail" or "RACE_XXX"). */
export function parseRaceErrorCode(message: string): string | null {
  const match = /(RACE_[A-Z_]+)/.exec(message);
  return match ? match[1]! : null;
}
